version: "3.9"

services:
  levell-zerobyte-web:
    image: ghcr.io/nicotsx/zerobyte:latest
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zerobyteLib:/var/lib/zerobyte
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true # enable traefik
        - traefik.swarm.network=traefik-public # put it in the same network as traefik
        - traefik.constraint-label=traefik-public # assign the same label as traefik so it can be discovered
        - traefik.http.routers.levellzerobyte.rule=Host(`zerobyte.app.levell.ch`) # listen to port 80 for request to APP_DOMAIN (use together with the line below)
        - traefik.http.routers.levellzerobyte.entrypoints=http
        - traefik.http.routers.levellzerobyte.middlewares=https-redirect
        - traefik.http.middlewares.levellzerobyte.redirectscheme.scheme=https # redirect traffic to https
        - traefik.http.middlewares.levellzerobyte.redirectscheme.permanent=true # redirect traffic to https
        - traefik.http.routers.levellzerobyte-secured.rule=Host(`zerobyte.app.levell.ch`) # listen to port 443 for request to APP_DOMAIN (use together with the line below)
        - traefik.http.routers.levellzerobyte-secured.entrypoints=https
        - traefik.http.routers.levellzerobyte-secured.tls.certresolver=le # use the Let's Encrypt certificate we set up earlier
        - traefik.http.services.levellzerobyte-secured.loadbalancer.server.port=4096 # ask Traefik to search for port service container

networks:
  traefik-public:
    external: true

volumes:
  zerobyteLib:
    driver: local
    driver_opts:
      type: none
      device: /srv/docker/zerobyte/lib
      o: bind
